### ISSUE TITLE
The CompressionComponent.php throws an error when starting Neos 5.0

### ISSUE THREAD

**Issue by rr-appadaptive** [CarbonPackages/Carbon.Compression#3]
Warning: strpos() expects parameter 1 to be string, array given in /app/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Carbon_Compression_Flow_Http_Component_CompressionComponent.php line 40

The error seems to be caused by an update of the Doctrine-Orm from Version 2.6.3 to Version 2.6.4 because other users reported similar errors today.

**Comment by jonnitto** [comment]
Thankx, I will look at it.

**Comment by rr-appadaptive** [comment]
I just read in the docs of the psr7 Http-message-interfaces which is obviously used in the CompressionComponent.php that the method "getHeader()" returns an array if it has more than one header added.
To force this interface to return a string the method "getHeaderLine()" is recommended as it forcibly returns a string.

**Comment by jonnitto** [comment]
Solved with version [2.0.0](https://github.com/CarbonPackages/Carbon.Compression/releases/tag/2.0.0)
