### ISSUE TITLE
X-Compression Header not set because of wrong loading order

### ISSUE THREAD

**Issue by dlubitz** [CarbonPackages/Carbon.Compression#8]
As the `neos/neos` dependency is not set in [composer.json](https://github.com/CarbonPackages/Carbon.Compression/blob/master/composer.json#L12), the correct loading order of the packages is not guranteed.

If `carbon/compression` is loaded before `neos/neos` the [prototype ](https://github.com/CarbonPackages/Carbon.Compression/blob/master/Resources/Private/Fusion/Root.fusion#L5) get overriden/cleared by neos ([Page.fusion](https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Resources/Private/Fusion/Prototypes/Page.fusion#L3))

Only way I know to fix this is to set up `neos/neos` also as dependency, but this would make this package not work with flow (without neos) anymore.

**Comment by jonnitto** [comment]
Could you check, if it is fixed in `dev-master`?

**Comment by dlubitz** [comment]
Yes, it does. Nice thing.

**Comment by jonnitto** [comment]
Released. https://github.com/CarbonPackages/Carbon.Compression/releases/tag/4.0.1

**Comment by jonnitto** [comment]
Thanks for the report ❤️
